custody_cols <- c("custody_unsentenced_males",
                  "custody_unsentenced_females",
                  "total_under_custody_males",
                  "total_under_custody_females",
                  "custody_public_prisons_male",
                  "custody_public_prisons_female",
                  "custody_including_private_facilities_male",
                  "custody_including_private_facilities_female",
                  "custody_private_prison_male",
                  "custody_private_prison_female",
                  "custody_unsentenced_total",
                  "total_under_custody_total",
                  "custody_public_prisons_total",
                  "custody_private_prison_total")
custody_cols <- sort(custody_cols)

jurisdiction_cols <- c("jurisdiction_unsentenced_males",
                       "jurisdiction_unsentenced_females",
                       "total_under_jurisdiction_males",
                       "total_under_jurisdiction_females",
                       "jurisdiction_private_prison_in_state_male",
                       "jurisdiction_private_prison_in_state_female",
                       "jurisdiction_private_prison_out_of_state_male",
                       "jurisdiction_private_prison_out_of_state_female",
                       "jurisdiction_housed_in_local_facility_male",
                       "jurisdiction_housed_in_local_facility_female",
                       "jurisdiction_local_facilities_solely_to_ease_prison_crowding_male",
                       "jurisdiction_local_facilities_solely_to_ease_prison_crowding_female",
                       "jurisdiction_private_prison_male",
                       "jurisdiction_private_prison_female",
                       "jurisdiction_public_prison_male",
                       "jurisdiction_public_prison_female",
                       "jurisdiction_unsentenced_total",
                       "total_under_jurisdiction_total",
                       "jurisdiction_private_prison_total",
                       "jurisdiction_private_prison_out_of_state_total",
                       "jurisdiction_private_prison_in_state_total",
                       "jurisdiction_local_facilities_solely_to_ease_prison_crowding_total",
                       "jurisdiction_housed_in_local_facility_total",
                       "jurisdiction_public_prison_total")
jurisdiction_cols <- sort(jurisdiction_cols)

race_ethnicity_cols <- c("white_male",
                         "white_female",
                         "black_male",
                         "black_female",
                         "hispanic_or_latino_male",
                         "hispanic_or_latino_female",
                         "american_indian_male",
                         "american_indian_female",
                         "native_hawaiian_male",
                         "native_hawaiian_female",
                         "asian_male",
                         "asian_female",
                         "two_or_more_races_male",
                         "two_or_more_races_female",
                         "other_race_male",
                         "other_race_female",
                         "unknown_race_male",
                         "unknown_race_female",
                         "white_total",
                         "black_total",
                         "hispanic_or_latino_total",
                         "american_indian_total",
                         "native_hawaiian_total",
                         "asian_total",
                         "two_or_more_races_total",
                         "other_category_race_total",
                         "unknown_race_total")
race_ethnicity_cols <- sort(race_ethnicity_cols)

noncitizen_juvenile_cols <- c("in_custody_under_18_years_of_age_male",
                              "in_custody_under_18_years_of_age_female",
                              "in_custody_not_us_citizens_male",
                              "in_custody_not_us_citizens_female",
                              "in_custody_under_18_years_of_age_total",                                                              "in_custody_not_us_citizens_total")
noncitizen_juvenile_cols <- sort(noncitizen_juvenile_cols)

capacity_cols <- c("rated_capacity_male",
                   "rated_capacity_female",
                   "rated_capacity_total",
                   "operational_capacity_male",
                   "operational_capacity_female",
                   "operational_capacity_total",
                   "design_capacity_male",
                   "design_capacity_female",
                   "design_capacity_total")
capacity_cols <- sort(capacity_cols)

death_cols <- c("deaths_from_execution_male",
                "deaths_from_execution_female",
                "deaths_from_illness_or_natural_cause_male",
                "deaths_from_illness_or_natural_cause_female",
                "deaths_from_aids_male",
                "deaths_from_aids_female",
                "deaths_from_suicide_male",
                "deaths_from_suicide_female",
                "deaths_from_accidental_injury_to_self_male",
                "deaths_from_accidental_injury_to_self_female",
                "deaths_from_homicide_by_other_inmates_male",
                "deaths_from_homicide_by_other_inmates_female",
                "deaths_from_other_homicide_male",
                "deaths_from_other_homicide_female",
                "deaths_caused_by_another_person_male",
                "deaths_caused_by_another_person_female",
                "total_deaths_male",
                "total_deaths_female",
                "deaths_from_execution_total",
                "deaths_from_illness_or_natural_cause_total",
                "deaths_from_aids_total",
                "deaths_from_suicide_total",
                "deaths_from_accidental_injury_to_self_total",
                "deaths_from_homicide_by_other_inmates_total",
                "deaths_from_other_homicide_total",
                "deaths_caused_by_another_person_total",
                "total_deaths_total" )
death_cols <- sort(death_cols)

release_cols <- c("unconditional_release_expirations_of_sentence_male",
                  "unconditional_release_expirations_of_sentence_female",
                  "unconditional_release_commutations_male",
                  "unconditional_release_commutations_female",
                  "other_unconditional_release_male",
                  "other_unconditional_release_female",
                  "conditional_release_probations_male",
                  "conditional_release_probations_female",
                  "supervised_mandatory_release_male",
                  "supervised_mandatory_release_female",
                  "discretionary_parole_male",
                  "discretionary_parole_female",
                  "other_conditional_release_male",
                  "other_conditional_release_female",
                  "awol_release_male",
                  "awol_release_female",
                  "transfers_to_other_jurisdictions_male",
                  "transfers_to_other_jurisdictions_female",
                  "release_to_appeal_or_bond_male",
                  "release_to_appeal_or_bond_female",
                  "escape_from_confinement_male",
                  "escape_from_confinement_female",
                  "total_releases_male",
                  "total_releases_female",
                  "unconditional_release_expirations_of_sentence_total",
                  "unconditional_release_commutations_total",
                  "other_unconditional_release_total",
                  "conditional_release_probations_total",
                  "supervised_mandatory_release_total",
                  "discretionary_parole_total",
                  "other_conditional_release_total",
                  "awol_release_total",
                  "transfers_to_other_jurisdictions_total",
                  "release_to_appeal_or_bond_total",
                  "escape_from_confinement_total",
                  "total_releases_total")
release_cols <- sort(release_cols)

admission_cols <- c("new_court_commitments_male",
                    "new_court_commitments_female",
                    "parole_violators_with_new_sentence_male",
                    "parole_violators_with_new_sentence_female",
                    "parole_violators_without_new_sentence_male",
                    "parole_violators_without_new_sentence_female",
                    "other_conditional_release_violators_admitted_with_new_sentence_male",
                    "other_conditional_release_violators_admitted_with_new_sentence_female",
                    "other_conditional_release_violators_admitted_without_new_sentence_male",
                    "other_conditional_release_violators_admitted_without_new_sentence_female",
                    "transfers_admitted_from_other_jurisdictions_male",
                    "transfers_admitted_from_other_jurisdictions_female",
                    "awol_returns_with_or_without_new_sentences_male",
                    "awol_returns_with_or_without_new_sentences_female",
                    "escapee_returns_with_or_without_new_sentences_male",
                    "escapee_returns_with_or_without_new_sentences_female",
                    "returns_from_appeal_or_bond_male",
                    "returns_from_appeal_or_bond_female",
                    "other_admissions_male",
                    "other_admissions_female",
                    "total_admissions_male",
                    "total_admissions_female",
                    "new_court_commitments_total",
                    "parole_violators_with_new_sentence_total",
                    "parole_violators_without_new_sentence_total",
                    "other_conditional_release_violators_admitted_with_new_sentence_total",
                    "other_conditional_release_violators_admitted_without_new_sentence_total",
                    "transfers_admitted_from_other_jurisdictions_total",
                    "awol_returns_with_or_without_new_sentences_total",
                    "escapee_returns_with_or_without_new_sentences_total",
                    "returns_from_appeal_or_bond_total",
                    "other_admissions_total",
                    "total_admissions_total")
admission_cols <- sort(admission_cols)

aids_cols <- c("asymptomatic_hiv_positive_male",
               "asymptomatic_hiv_positive_female",
               "asymptomatic_hiv_positive_total",
               "infected_with_lesser_forms_of_symptomatic_hiv_disease_male",
               "infected_with_lesser_forms_of_symptomatic_hiv_disease_female",
               "infected_with_lesser_forms_of_symptomatic_hiv_disease_total",
               "confirmed_to_have_aids_male",
               "confirmed_to_have_aids_female",
               "confirmed_to_have_aids_total",
               "total_in_custody_hiv_positive_or_with_aids_male",
               "total_in_custody_hiv_positive_or_with_aids_female",
               "total_in_custody_hiv_positive_or_with_aids_total")
aids_cols <- sort(aids_cols)

prisoners_categories <- list(custody_cols,
                             jurisdiction_cols,
                             race_ethnicity_cols,
                             release_cols,
                             admission_cols,
                             capacity_cols,
                             noncitizen_juvenile_cols,
                             death_cols,
                             aids_cols)

# z <- names(prisoners)
# z <- z[!z %in% c("year", "state")]
# z <- z[!z %in% custody_cols]
# z <- z[!z %in% jurisdiction_cols]
# z <- z[!z %in% race_ethnicity_cols]
# z <- z[!z %in% release_cols]
# z <- z[!z %in% admission_cols]
# z <- z[!z %in% capacity_cols]
# z <- z[!z %in% noncitizen_juvenile_cols]
# z <- z[!z %in% death_cols]
# z <- z[!z %in% aids_cols]
# z

names(prisoners_categories) <- c("custody",
                                 "jurisdiction",
                                 "race_ethnicity",
                                 "release",
                                 "admission",
                                 "capacity",
                                 "noncitizen_juvenile",
                                 "death",
                                 "aids")


prisoners_name_fix <- c(
  "inmates_under_jurisdiction_housed_in_privately_operated_correctional_facility_in_state_male" = "jurisdiction_private_prison_in_state_male",
  "inmates_under_jurisdiction_housed_in_privately_operated_correctional_facility_in_state_female" = "jurisdiction_private_prison_in_state_female",
  "inmates_under_jurisdiction_housed_in_privately_operated_correctional_facility_in_other_state_male"                                                   = "jurisdiction_private_prison_out_of_state_male",
  "inmates_under_jurisdiction_housed_in_privately_operated_correctional_facility_in_other_state_female"                                                 = "jurisdiction_private_prison_out_of_state_female",
  "inmates_under_jurisdiction_housed_in_local_facilities_operated_by_county_or_other_local_authority_male"                                              = "jurisdiction_housed_in_local_facility_male",
  "inmates_under_jurisdiction_housed_in_local_facilities_operated_by_county_or_other_local_authority_female"                                            = "jurisdiction_housed_in_local_facility_female",
  "local_facilities_solely_to_ease_prison_crowding_male" = "jurisdiction_local_facilities_solely_to_ease_prison_crowding_male",
  "local_facilities_solely_to_ease_prison_crowding_female" = "jurisdiction_local_facilities_solely_to_ease_prison_crowding_female",
  "american_indian_or_alaska_native_male"            = "american_indian_male",
  "american_indian_or_alaska_native_female"          = "american_indian_female",
  "native_hawaiian_or_other_pacific_islander_male"   = "native_hawaiian_male",
  "native_hawaiian_or_other_pacific_islander_female" = "native_hawaiian_female",
  "asian_or_pacific_islander_male"                   = "asian_male",
  "asian_or_pacific_islander_female"                 = "asian_female",
  "additional_other_categories_for_race_male"        = "other_race_male",
  "additional_other_categories_for_race_female"      = "other_race_female",
  "custody_excluding_private_facilities_male"        = "custody_public_prisons_male",
  "custody_excluding_private_facilities_female"      = "custody_public_prisons_female",
  "in_custody_not_u_s_citizens_male"                 = "in_custody_not_us_citizens_male",
  "in_custody_not_u_s_citizens_female"               = "in_custody_not_us_citizens_female"
)
