all_unique_arrest_cols <- c("agg_assault",
                            "all_other",
                            "oth_assault",
                            "arson",
                            "burglary",
                            "curfew_loiter",
                            "disorder_cond",
                            "total_drug",
                            "drunkenness",
                            "dui",
                            "embezzlement",
                            "family_off",
                            "forgery",
                            "fraud",
                            "gamble_total",
                            "liquor",
                            "manslaught_neg",
                            "mtr_veh_theft",
                            "murder",
                            "prostitution",
                            "rape",
                            "robbery",
                            "runaways",
                            "oth_sex_off",
                            "stolen_prop",
                            "suspicion",
                            "theft",
                            "vagrancy",
                            "vandalism",
                            "weapons")

arrest_categories <- c("tot_adult",
                       "tot_juv",
                       "tot_arrests",
                       "tot_female_adult",
                       "tot_male_adult",
                       "tot_female_juv",
                       "tot_male_juv",
                       "tot_female",
                       "tot_male",
                       "adult_amer_ind",
                       "adult_asian",
                       "adult_black",
                       "adult_white",
                       "juv_amer_ind",
                       "juv_asian",
                       "juv_black",
                       "juv_white",
                       "tot_amer_ind",
                       "tot_asian",
                       "tot_black",
                       "tot_white")



hate_crimes_offenses_fix <- c(

  "^aggravated assault"                                  = "violent",
  "^all other larceny"                                   = "nonviolent",
  "^arson"                                               = "nonviolent",
  "^assisting or promoting prostitution"                 = "violent",
  "^bribery"                                             = "nonviolent",
  "^burglary/breaking and entering"                      = "nonviolent",
  "^fraud-other"                                         = "nonviolent",
  "^theft-other"                                         = "nonviolent",
  "^counterfeiting/forgery"                              = "nonviolent",
  "^credit card/atm fraud"                               = "nonviolent",
  "^destruction of property/vandalism"                   = "nonviolent",
  "^drug equipment violations"                           = "nonviolent",
  "^drug/narcotic violations"                            = "nonviolent",
  "^embezzlement"                                        = "nonviolent",
  "^extortion/blackmail"                                 = "nonviolent",
  "^false pretenses/swindle/confidence game"             = "nonviolent",
  "^forcible fondling - indecent liberties/child molest" = "violent",
  "^forcible rape"                                       = "violent",
  "^forcible sodomy"                                     = "violent",
  "^human trafficking - commercial sex acts"             = "violent",
  "^impersonation"                                       = "nonviolent",
  "^incest"                                              = "violent",
  "^intimidation"                                        = "violent",
  "^kidnapping/abduction"                                = "violent",
  "^motor vehicle theft"                                 = "nonviolent",
  "^murder/non-negligent manslaughter"                   = "violent",
  "^negligent manslaughter"                              = "violent",
  "^pocket-picking"                                      = "nonviolent",
  "^pornography/obscene material"                        = "violent",
  "^prostitution"                                        = "violent",
  "^purchasing prostitution"                             = "violent",
  "^purse-snatching"                                     = "nonviolent",
  "^robbery"                                             = "violent",
  "^sexual assault with an object"                       = "violent",
  "^shoplifting"                                         = "nonviolent",
  "^simple assault"                                      = "violent",
  "^statutory rape"                                      = "violent",
  "^stolen property offenses - receiving, selling, etc." = "nonviolent",
  "^theft from building"                                 = "nonviolent",
  "^theft from coin-operated machine or device"          = "nonviolent",
  "^theft from motor vehicle"                            = "nonviolent",
  "^theft of motor vehicle parts/accessories"            = "nonviolent",
  "^weapon law violations"                               = "nonviolent",
  "^welfare fraud"                                       = "nonviolent",
  "^wire fraud"                                          = "nonviolent"
)


starting_cols <- c("agency",
                   "year",
                   "state",
                   "population",
                   "ORI")

ucr_to_drop <- c("state_abb",
                 "ORI9",
                 "FIPS_state_code",
                 "FIPS_county_code",
                 "months_reported",
                 "fips_state_county_code",
                 "fips_place_code",
                 "fips_state_place_code",
                 "division",
                 "core_city_indication",
                 "covered_by_code",
                 "population_1",
                 "county_1",
                 "msa_1",
                 "population_2",
                 "county_2",
                 "msa_2",
                 "population_3",
                 "county_3",
                 "msa_3",
                 "followup_indication",
                 "special_mailing_group",
                 "special_mailing_address",
                 "mailing_address_line_1",
                 "mailing_address_line_2",
                 "mailing_address_line_3",
                 "mailing_address_line_4",
                 "agency_type",
                 "agency_subtype_1",
                 "agency_subtype_2",
                 "group_number",
                 "agency_state_name",
                 "agency_name",
                 "field_office",
                 "total_population",
                 "city_sequence_number",
                 "last_update",
                 "field_office",
                 "zip_code")

arrests_to_drop <- c("ori9",
                     "agency_name",
                     "state_abb",
                     "fips_state_code",
                     "fips_county_code",
                     "fips_state_county_code",
                     "fips_place_code",
                     "fips_state_place_code",
                     "agency_type",
                     "agency_subtype_1",
                     "agency_subtype_2",
                     "group",
                     "geographic_division",
                     "suburban_agency",
                     "core_city",
                     "covered_by_another_agency")

