all_unique_arrest_cols <- c("agg_assault",
                            "all_other",
                            "oth_assault",
                            "arson",
                            "burglary",
                            "curfew_loiter",
                            "disorder_cond",
                            "total_drug",
                            "drunkenness",
                            "dui",
                            "embezzlement",
                            "family_off",
                            "forgery",
                            "fraud",
                            "gamble_total",
                            "liquor",
                            "manslaught_neg",
                            "mtr_veh_theft",
                            "murder",
                            "prostitution",
                            "rape",
                            "robbery",
                            "runaways",
                            "oth_sex_off",
                            "stolen_prop",
                            "suspicion",
                            "theft",
                            "vagrancy",
                            "vandalism",
                            "weapons")

arrest_categories <- c("tot_adult",
                       "tot_juv",
                       "tot_arrests",
                       "tot_female_adult",
                       "tot_male_adult",
                       "tot_female_juv",
                       "tot_male_juv",
                       "tot_female",
                       "tot_male",
                       "adult_amer_ind",
                       "adult_asian",
                       "adult_black",
                       "adult_white",
                       "juv_amer_ind",
                       "juv_asian",
                       "juv_black",
                       "juv_white",
                       "tot_amer_ind",
                       "tot_asian",
                       "tot_black",
                       "tot_white")



hate_crimes_offenses_fix <- c(
  "^arson$" = "arson",
  "^assault offenses - aggravated assault$" = "assault",
  "^assault offenses - intimidation$" = "assault",
  "^assault offenses - simple assault$" = "assault",
  "^bribery$" = "bribery",
  "^burglary/breaking and entering$" = "burglary/breaking and entering",
  "^counterfeiting/forgery$" = "fraud",
  "^destruction/damage/vandalism of property$" = "fraud",
  "^drug/narcotic offenses - drug equipment violations$" = "drug offense",
  "^drug/narcotic offenses - drug/narcotic violations$" = "drug offense",
  "^embezzlement$" = "fraud",
  "^extortion/blackmail$" = "extortion/blackmail",
  "^fraud offenses - credit card/atm fraud$" = "fraud",
  "^fraud offenses - false pretenses/swindle/confidence game$" = "fraud",
  "^fraud offenses - impersonation$" = "fraud",
  "^fraud offenses - other$" = "fraud",
  "^fraud offenses - welfare fraud$" = "fraud",
  "^fraud offenses - wire fraud$" = "fraud",
  "^gambling offenses - betting/wagering$" = "gambling offenses",
  "^human trafficking - commercial sex acts$" = "human trafficking",
  "^human trafficking - involuntary servitude$" = "human trafficking",
  "^kidnapping/abduction$" = "kidnapping/abduction",
  "^larceny/theft offenses - all other larceny$" = "theft",
  "^larceny/theft offenses - other$" = "theft",
  "^larceny/theft offenses - pocket-picking$" = "theft",
  "^larceny/theft offenses - purse-snatching$" = "theft",
  "^larceny/theft offenses - shoplifting$" = "theft",
  "^larceny/theft offenses - theft from building$" = "theft",
  "^larceny/theft offenses - theft from motor vehicle$" = "theft",
  "^larceny/theft offenses - theft of motor vehicle parts/accessories$" = "theft",
  "^larceny/theft offenses - theft rom coin-operated machine or device$" = "theft",
  "^motor vehicle theft$" = "motor vehicle theft",
  "^murder/nonnegligent manslaughter$" = "murder/nonnegligent manslaughter",
  "^negligent manslaughter$" = "negligent manslaughter",
  "^pornography/obscene material$" = "pornography/obscene material",
  "^prostitution offenses - assisting or promoting prostitution$" = "prostitution",
  "^prostitution offenses - prostitution$" = "prostitution",
  "^prostitution offenses - purchasing prostitution$" = "prostitution",
  "^robbery$" = "robbery",
  "^sex offenses - fondling - indecent liberties/child molest$" = "sex offense",
  "^sex offenses - incest$" = "sex offenses",
  "^sex offenses - rape$" = "sex offenses",
  "^sex offenses - sexual assault with an object$" = "sex offenses",
  "^sex offenses - sodomy$" = "sex offenses",
  "^sex offenses - statutory rape$" = "sex offenses",
  "^stolen property offenses (receiving, selling, etc.)$" = "stolen property offenses",
  "^weapon law violations$" = "weapon law violations"
)


starting_cols <- c("agency",
                   "year",
                   "state",
                   "population",
                   "ORI")

ucr_to_drop <- c("state_abb",
                 "ORI9",
                 "FIPS_state_code",
                 "FIPS_county_code",
                 "months_reported",
                 "fips_state_county_code",
                 "fips_place_code",
                 "fips_state_place_code",
                 "division",
                 "core_city_indication",
                 "covered_by_code",
                 "population_1",
                 "county_1",
                 "msa_1",
                 "population_2",
                 "county_2",
                 "msa_2",
                 "population_3",
                 "county_3",
                 "msa_3",
                 "followup_indication",
                 "special_mailing_group",
                 "special_mailing_address",
                 "mailing_address_line_1",
                 "mailing_address_line_2",
                 "mailing_address_line_3",
                 "mailing_address_line_4",
                 "agency_type",
                 "agency_subtype_1",
                 "agency_subtype_2",
                 "group_number",
                 "agency_state_name",
                 "agency_name",
                 "field_office",
                 "total_population",
                 "city_sequence_number",
                 "last_update",
                 "field_office",
                 "zip_code")

arrests_to_drop <- c("ori9",
                     "agency_name",
                     "state_abb",
                     "fips_state_code",
                     "fips_county_code",
                     "fips_state_county_code",
                     "fips_place_code",
                     "fips_state_place_code",
                     "agency_type",
                     "agency_subtype_1",
                     "agency_subtype_2",
                     "group",
                     "geographic_division",
                     "suburban_agency",
                     "core_city",
                     "covered_by_another_agency")

