cause_of_death_fix <- c(
  "^Alcohol-induced causes$"                                     = "alcohol_total",
  "^Alcohol poisonings \\(overdose\\) \\(X45, X65, Y15\\)$"      = "alcohol_overdose",
  "^All other alcohol-induced causes$"                           = "alcohol_all_other",
  "^All other drug-induced causes$"                              = "drugs_all_other",
  "^Drug-induced causes$"                                        = "drugs_total",
  "^Drug and Alcohol - Total$"                                   = "drugs_and_alcohol_total",
  "^Drug poisonings \\(overdose\\) Homicide \\(X85\\)$"          = "drugs_overdose_homicide",
  "^Drug poisonings \\(overdose\\) Suicide \\(X60-X64\\)$"       = "drugs_overdose_suicide",
  "^Drug poisonings \\(overdose\\) Undetermined \\(Y10-Y14\\)$"  = "drugs_overdose_undetermined",
  "^Drug poisonings \\(overdose\\) Unintentional \\(X40-X44\\)$" = "drugs_overdose_unintentional",
  "^Unintentional$" = "total_unintentional",
  "^Suicide$"       = "total_suicide",
  "^Homicide$"      = "total_homicide",
  "^Undetermined$"  = "total_undetermined"
)


hate_crimes_offenses_fix <- c(
  "^aggravated assault"                                  = "violent",
  "^all other larceny"                                   = "nonviolent",
  "^arson"                                               = "nonviolent",
  "^assisting or promoting prostitution"                 = "sexual",
  "^bribery"                                             = "nonviolent",
  "^burglary/breaking and entering"                      = "nonviolent",
  "^counterfeiting/forgery"                              = "nonviolent",
  "^credit card/atm fraud"                               = "nonviolent",
  "^destruction of property/vandalism"                   = "nonviolent",
  "^drug equipment violations"                           = "nonviolent",
  "^drug/narcotic violations"                            = "nonviolent",
  "^embezzlement"                                        = "nonviolent",
  "^extortion/blackmail"                                 = "nonviolent",
  "^false pretenses/swindle/confidence game"             = "nonviolent",
  "^forcible fondling - indecent liberties/child molest" = "sexual",
  "^forcible rape"                                       = "sexual",
  "^forcible sodomy"                                     = "sexual",
  "^human trafficking - commercial sex acts"             = "sexual",
  "^impersonation"                                       = "nonviolent",
  "^incest"                                              = "sexual",
  "^intimidation"                                        = "violent",
  "^kidnapping/abduction"                                = "violent",
  "^motor vehicle theft"                                 = "nonviolent",
  "^murder/non-negligent manslaughter"                   = "violent",
  "^negligent manslaughter"                              = "violent",
  "^pocket-picking"                                      = "nonviolent",
  "^pornography/obscene material"                        = "sexual",
  "^prostitution"                                        = "sexual",
  "^purchasing prostitution"                             = "sexual",
  "^purse-snatching"                                     = "nonviolent",
  "^robbery"                                             = "violent",
  "^sexual assault with an object"                       = "sexual",
  "^shoplifting"                                         = "nonviolent",
  "^simple assault"                                      = "violent",
  "^statutory rape"                                      = "sexual",
  "^stolen property offenses - receiving, selling, etc." = "nonviolent",
  "^theft from building"                                 = "nonviolent",
  "^theft from coin-operated machine or device"          = "nonviolent",
  "^theft from motor vehicle"                            = "nonviolent",
  "^theft of motor vehicle parts/accessories"            = "nonviolent",
  "^weapon law violations"                               = "nonviolent",
  "^welfare fraud"                                       = "nonviolent",
  "^wire fraud"                                          = "nonviolent"
)


starting_cols <- c("agency",
                   "year",
                   "state",
                   "population",
                   "ORI")

ucr_to_drop <- c("state_abb",
                 "ORI9",
                 "FIPS_state_code",
                 "FIPS_county_code",
                 "months_reported",
                 "fips_state_county_code",
                 "fips_place_code",
                 "fips_state_place_code",
                 "division",
                 "core_city_indication",
                 "covered_by_code",
                 "population_1",
                 "county_1",
                 "msa_1",
                 "population_2",
                 "county_2",
                 "msa_2",
                 "population_3",
                 "county_3",
                 "msa_3",
                 "followup_indication",
                 "special_mailing_group",
                 "special_mailing_address",
                 "mailing_address_line_1",
                 "mailing_address_line_2",
                 "mailing_address_line_3",
                 "mailing_address_line_4",
                 "agency_type",
                 "agency_subtype_1",
                 "agency_subtype_2",
                 "group_number",
                 "agency_state_name",
                 "agency_name",
                 "field_office",
                 "total_population",
                 "city_sequence_number",
                 "last_update",
                 "field_office",
                 "zip_code")

arrests_to_drop <- c("ori9",
                     "agency_name",
                     "state_abb",
                     "fips_state_code",
                     "fips_county_code",
                     "fips_state_county_code",
                     "fips_place_code",
                     "fips_state_place_code",
                     "agency_type",
                     "agency_subtype_1",
                     "agency_subtype_2",
                     "group",
                     "geographic_division",
                     "suburban_agency",
                     "core_city",
                     "covered_by_another_agency")

